object Versions {
    const val coreKtx = "1.9.0"
    const val appcompat = "1.6.1"
    const val kotlinJdk = "1.8.10"
    const val jUnit = "4.13.2"
    const val jUnitTest = "1.1.5"
    const val espresso = "3.5.1"
    const val uiTest = "1.3.3"
    const val androidTools = "7.4.2"
    const val kotlinPlugin = "1.8.10"
    const val kotlinGradle = "1.8.0"
    const val hiltPlugin = "2.50"
    const val hiltCompiler = "2.50"
    const val constraintLayout = "1.0.1"
    const val room = "2.6.1"
    const val mockitoCore = "2.11.0"
    const val mockitoKotlin = "4.1.0"
    const val mockitoInLine = "5.2.0"
    const val coroutinesTest = "1.7.1"
    const val navigation = "2.5.3"
    const val retrofit2 = "2.9.0"
    const val hiltAndroidTesting = "2.50"
    const val hiltAndroidCompilerTesting = "2.50"
    const val robolectric = "4.11.1"
    const val roomTest = "2.2.6"
    const val expressoResource = "3.5.1"
}
